fetch('https://pytml.vercel.app/api/count')
  .then(r => r.json())
  .then(data => console.log('Pytml loaded:', data.message, 'times'))
  .catch(() => {});
/*
 * Pytml 3.0.0 - Python + HTML
 * https://pytml.js.org   (MIT/Apache-2.0, see LICENSE)
 *
 * This file is GENERATED by build.js from compiler/pytml.src.js,
 * compiler/compiler.py, compiler/runtime.py and compiler/tfjs_bridge.py.
 * Edit those files, not this one.
 */
(function (window) {
    'use strict';

    const VERSION = '3.0.0';
    const PYODIDE_VERSION = '314.0.7';
    const CONFIG = window.PYTML_CONFIG || {};
    const PYODIDE_INDEX = CONFIG.indexURL || ('https://cdn.jsdelivr.net/pyodide/v' + PYODIDE_VERSION + '/full/');
    const TFJS_URL = CONFIG.tfjsURL || 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js';
    const EVENTS = ['click', 'dblclick', 'input', 'change', 'submit', 'keydown', 'keyup', 'keypress',
        'focusin', 'focusout', 'mouseover', 'mouseout', 'mousedown', 'mouseup', 'pointerdown', 'pointerup',
        'touchstart', 'touchend', 'contextmenu'];
    const BLOCK_TAG = /^py\d*$/i;

    // ---- the Python half of Pytml (embedded by build.js) -------------------
    const PY_COMPILER = /*PY_COMPILER*/'';
    const PY_RUNTIME = /*PY_RUNTIME*/'';
    const PY_TFJS = /*PY_TFJS*/'';

    class PYTML {
        constructor() {
            this.version = VERSION;
            this.out = null;
            this.statusEl = null;
            this.pyodide = null;
            this.rt = null;
            this.ready = false;
            this.done = false;
            this.cursor = null;       // current line of output (so print(end="") works)
            this.tfPromise = null;
            this.init();
        }

        // ------------------------------------------------------------------
        //  start-up
        // ------------------------------------------------------------------
        async init() {
            this.makeConsole();
            this.status('Loading Python ...');
            try {
                const blocks = this.findBlocks();
                this.wireEvents();
                await this.loadPyodide();
                this.status('Starting Pytml ...');
                this.installPython();
                this.ready = true;
                const sources = [];
                for (const b of blocks) sources.push(await this.sourceOf(b));
                this.rt.load(blocks.map((_, i) => String(i + 1)), sources);
                this.status('');
                for (let i = 0; i < blocks.length; i++) {
                    await this.rt.run_block(String(i + 1));
                }
                this.done = true;
                window.dispatchEvent(new Event('pytml-done'));
            } catch (error) {
                this.status('');
                this.error('Pytml could not start: ' + (error && error.message || error));
                console.error('[PYTML]', error);
            }
        }

        findBlocks() {
            const out = [];
            for (const el of document.querySelectorAll('*')) {
                const tag = el.tagName.toLowerCase();
                if (BLOCK_TAG.test(tag) || (tag === 'script' && /^(text\/python|py)$/i.test(el.type))) {
                    out.push(el);
                }
            }
            return out;
        }

        async sourceOf(el) {
            const src = el.getAttribute('src');
            if (!src) return el.textContent;
            if (location.protocol === 'file:') {
                throw new Error('"' + src + '" cannot be loaded from a file:// page. Put the Python inside the <py> tag, or open the page through a web server.');
            }
            const res = await fetch(src);
            if (!res.ok) throw new Error('Could not load ' + src + ' (HTTP ' + res.status + ')');
            return await res.text();
        }

        loadScript(url) {
            return new Promise((resolve, reject) => {
                const s = document.createElement('script');
                s.src = url;
                s.onload = resolve;
                s.onerror = () => reject(new Error('Could not load ' + url));
                document.head.appendChild(s);
            });
        }

        async loadPyodide() {
            if (typeof window.loadPyodide === 'undefined') {
                await this.loadScript(PYODIDE_INDEX + 'pyodide.js');
            }
            this.pyodide = await window.loadPyodide({ indexURL: PYODIDE_INDEX });
            window.pyodide = this.pyodide;
        }

        installPython() {
            window.pytml = this;               // Python reaches the page through js.pytml
            const py = this.pyodide;
            py.globals.set('_pt_compiler_src', PY_COMPILER);
            py.globals.set('_pt_runtime_src', PY_RUNTIME);
            py.runPython(
                'import sys, types\n' +
                'def _pt_module(name, src):\n' +
                '    m = types.ModuleType(name)\n' +
                '    sys.modules[name] = m\n' +
                '    exec(compile(src, "<pytml " + name + ">", "exec"), m.__dict__)\n' +
                '    return m\n' +
                '_pt_module("pytml_compiler", _pt_compiler_src)\n' +
                '_pt_rt = _pt_module("pytml_runtime", _pt_runtime_src)\n' +
                '_pt_rt = _pt_rt.RUNTIME\n'
            );
            this.rt = py.globals.get('_pt_rt');
        }

        // ------------------------------------------------------------------
        //  events:  <button py-click="function_name">
        // ------------------------------------------------------------------
        wireEvents() {
            for (const type of EVENTS) {
                document.addEventListener(type, (ev) => {
                    if (!this.ready || !this.rt) return;
                    const attr = 'py-' + (type === 'focusin' ? 'focus' : type === 'focusout' ? 'blur' : type);
                    const el = ev.target && ev.target.closest ? ev.target.closest('[' + attr + ']') : null;
                    if (!el) return;
                    if (type === 'submit') ev.preventDefault();
                    this.rt.run_attribute(attr.slice(3), el.getAttribute(attr), ev);
                }, true);
            }
        }

        // ------------------------------------------------------------------
        //  console / output area (print, input, pick, show)
        // ------------------------------------------------------------------
        makeConsole() {
            let box = document.getElementById('pytml-output');
            if (!box) {
                box = document.createElement('div');
                box.id = 'pytml-output';
                box.className = 'pytml-output';
                const style = document.createElement('style');
                style.textContent = `
                    py, py1, py2, py3, py4, py5, py6, py7, py8, py9 { display: none; }
                    .pytml-output { background:#0a0e27; border-radius:15px; padding:20px; margin:20px 0;
                        font-family:'Courier New',monospace; font-size:14px; line-height:1.5;
                        box-shadow:0 10px 40px rgba(0,0,0,.3); border:1px solid rgba(102,126,234,.3);
                        max-height:500px; overflow-y:auto; color:#e0e0e0; white-space:pre-wrap; word-break:break-word; }
                    .pytml-output:empty { display:none; }
                    .pytml-output .pytml-error { color:#fa709a; background:rgba(250,112,154,.15);
                        padding:10px; margin:10px 0; border-radius:8px; display:block; }
                    .pytml-output .pytml-ask { display:flex; flex-wrap:wrap; gap:8px; align-items:center;
                        background:rgba(102,126,234,.1); border:1px solid rgba(102,126,234,.3);
                        border-radius:10px; padding:12px; margin:10px 0; white-space:normal; }
                    .pytml-output .pytml-prompt { color:#ffd93d; font-family:system-ui,sans-serif; flex:1 1 100%; }
                    .pytml-output input { flex:1; min-width:120px; padding:10px 12px; background:rgba(255,255,255,.1);
                        border:1px solid rgba(102,126,234,.5); border-radius:8px; color:#fff; font:inherit; outline:none; }
                    .pytml-output button { background:linear-gradient(135deg,#667eea 0%,#764ba2 100%); border:0;
                        padding:10px 20px; border-radius:8px; color:#fff; font:600 14px system-ui,sans-serif;
                        cursor:pointer; touch-action:manipulation; }
                    .pytml-output img { max-width:100%; background:#fff; border-radius:8px; margin:6px 0; display:block; }
                    .pytml-output table { border-collapse:collapse; background:#fff; color:#111; margin:6px 0; }
                    .pytml-output th, .pytml-output td { border:1px solid #ccc; padding:4px 8px; }
                    .pytml-status { position:fixed; bottom:20px; right:20px; background:#667eea; color:#fff;
                        padding:8px 16px; border-radius:20px; font:12px monospace; z-index:9999; max-width:80vw; }`;
                document.head.appendChild(style);
                const first = document.querySelector('*') && this.findBlocks()[0];
                if (first) first.insertAdjacentElement('beforebegin', box); else document.body.appendChild(box);
            }
            this.out = box;
        }

        hideConsoleIfEmpty() { /* .pytml-output:empty is hidden by CSS */ }

        target() { return this.out; }
        refresh() { /* hook for future reactive features */ }

        write(text, isError) {
            if (!this.out) return;
            const parts = String(text).split('\n');
            parts.forEach((part, i) => {
                if (part) this.appendText(part, isError);
                if (i < parts.length - 1) this.appendText('\n', isError);
            });
            this.out.scrollTop = this.out.scrollHeight;
        }

        appendText(text, isError) {
            let last = this.out.lastChild;
            if (isError) {
                last = document.createElement('span');
                last.className = 'pytml-error';
                last.textContent = text;
                this.out.appendChild(last);
            } else if (last && last.nodeType === 3) {
                last.appendData(text);
            } else {
                this.out.appendChild(document.createTextNode(text));
            }
        }

        error(text) {
            if (!this.out) { console.error(text); return; }
            const span = document.createElement('span');
            span.className = 'pytml-error';
            span.textContent = text;
            this.out.appendChild(span);
            this.out.appendChild(document.createTextNode('\n'));
            console.error('[PYTML]\n' + text);
        }

        clear() { if (this.out) this.out.textContent = ''; }

        html(markup) {
            const div = document.createElement('div');
            div.innerHTML = markup;
            this.out.appendChild(div);
        }

        image(url) {
            const img = document.createElement('img');
            img.src = url;
            this.out.appendChild(img);
        }

        status(message) {
            if (!message) {
                if (this.statusEl) { this.statusEl.remove(); this.statusEl = null; }
                return;
            }
            if (!this.statusEl) {
                this.statusEl = document.createElement('div');
                this.statusEl.className = 'pytml-status';
                document.body.appendChild(this.statusEl);
            }
            this.statusEl.textContent = message;
        }

        // input("question") -> Promise<string>
        input(prompt) {
            return new Promise((resolve) => {
                const box = document.createElement('div');
                box.className = 'pytml-ask';
                if (prompt) {
                    const p = document.createElement('div');
                    p.className = 'pytml-prompt';
                    p.textContent = prompt;
                    box.appendChild(p);
                }
                const field = document.createElement('input');
                field.type = 'text';
                field.placeholder = 'Type here and press Enter';
                const btn = document.createElement('button');
                btn.textContent = 'OK';
                box.appendChild(field);
                box.appendChild(btn);
                this.out.appendChild(box);
                const done = () => {
                    const value = field.value;
                    box.remove();
                    this.appendText((prompt || '') + value + '\n', false);
                    resolve(value);
                };
                btn.addEventListener('click', done);
                field.addEventListener('keydown', (e) => { if (e.key === 'Enter') done(); });
                field.focus();
                if (box.scrollIntoView) box.scrollIntoView({ block: 'nearest' });
            });
        }

        // pick("question", ["+", "-"]) -> Promise<index>
        pick(prompt, options) {
            return new Promise((resolve) => {
                const box = document.createElement('div');
                box.className = 'pytml-ask';
                if (prompt) {
                    const p = document.createElement('div');
                    p.className = 'pytml-prompt';
                    p.textContent = prompt;
                    box.appendChild(p);
                }
                Array.from(options).forEach((label, i) => {
                    const b = document.createElement('button');
                    b.textContent = label;
                    b.addEventListener('click', () => {
                        box.remove();
                        this.appendText((prompt ? prompt + ' ' : '') + label + '\n', false);
                        resolve(i);
                    });
                    box.appendChild(b);
                });
                this.out.appendChild(box);
                if (box.scrollIntoView) box.scrollIntoView({ block: 'nearest' });
            });
        }

        // ------------------------------------------------------------------
        //  TensorFlow.js (used by `import tensorflow as tf`)
        // ------------------------------------------------------------------
        tfSource() { return PY_TFJS; }

        ensureTF() {
            if (window.tf) return Promise.resolve();
            if (!this.tfPromise) {
                this.status('Loading TensorFlow.js ...');
                this.tfPromise = this.loadScript(TFJS_URL).then(() => this.status(''));
            }
            return this.tfPromise;
        }

        // ------------------------------------------------------------------
        //  public helpers for developers
        // ------------------------------------------------------------------
        run(code) {                       // pytml.run("print(1)") from JavaScript
            const name = 'js' + Date.now();
            this.rt.load([name], [code]);
            return this.rt.run_block(name);
        }
    }

    function start() {
        if (!window.pytml || !(window.pytml instanceof PYTML)) new PYTML();
    }

    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
    else start();
})(window);
