name: Pytml Bot

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  mention:
    runs-on: ubuntu-latest
    steps:
      - name: Pytml Bot
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.issue.number;
            const opener = context.payload.sender.login; // the user who opened

            const body = `Hello @${opener},

First off thanks for showing interest in our project.

Your request will be reviewed by @nodex-ar soon as he becomes free.

Once again thanks and just leave us a star and help us !`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body,
            });
